clean build before making deb, preinst removed

diff --git a/make_deb b/make_deb
--- a/make_deb
+++ b/make_deb
@@ -16,7 +16,7 @@
 ## limitations under the License.
 ##--------------------------------------------------------------------
 ##
-## Author: Massimiliano Pinto
+## Author: Massimiliano Pinto, Vaibhav Singhal
 ##
 
 set -e
@@ -99,35 +99,25 @@ if [ ! -L "${BUILD_ROOT}" -a ! -d "${BUILD_ROOT}" ]; then
     mkdir -p "${BUILD_ROOT}"
 fi
 
-# Check plugin has been built
-if [ ! -d "${GIT_ROOT}/build" ]; then
-    echo "Warning: ./build directory not found."
-    echo "Building plugin ${plugin_name} first."
-    # Check FOGLAMP_ROOT
-    if [ -z ${FOGLAMP_ROOT+x} ]; then
-        # Set FOGLAMP_ROOT as the default directory
-        FOGLAMP_ROOT="/usr/local/foglamp"
-        export FOGLAMP_ROOT
-    fi
 
-    # Check if the default directory exists
-    if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-        logger -p local0.err -t "foglamp.script.foglamp" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
-        echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
-        echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
-        echo "Specify the base directory for FogLAMP and set the variable with:"
-        echo "export FOGLAMP_ROOT=<basedir>"
-        exit 1
-    fi
-
-    # Check/set LD_LIBRARY_PATH
-    libPathSet=0
-    libdir=${FOGLAMP_ROOT}/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
-    libdir=${FOGLAMP_ROOT}/cmake_build/C/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
-    [ "$libPathSet" -eq "0" ] && echo "Unable to set/update LD_LIBRARY_PATH to include path of Foglamp shared libraries: check whether ${FOGLAMP_ROOT}/lib or ${FOGLAMP_ROOT}/cmake_build/C/lib exists" && exit 1
-
-    mkdir ./build; cd ./build; cmake ..; make; cd ..
+# Check if the default directory exists
+if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
+    logger -p local0.err -t "foglamp.script.foglamp" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
+    echo "Specify the base directory for FogLAMP and set the variable with:"
+    echo "export FOGLAMP_ROOT=<basedir>"
+    exit 1
 fi
+
+# Check/set LD_LIBRARY_PATH
+libPathSet=0
+libdir=${FOGLAMP_ROOT}/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
+libdir=${FOGLAMP_ROOT}/cmake_build/C/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
+[ "$libPathSet" -eq "0" ] && echo "Unable to set/update LD_LIBRARY_PATH to include path of Foglamp shared libraries: check whether ${FOGLAMP_ROOT}/lib or ${FOGLAMP_ROOT}/cmake_build/C/lib exists" && exit 1
+
+rm -rf build; mkdir ./build; cd ./build; cmake ..; make; cd ..
+
 
 cd "${BUILD_ROOT}"
 existing_pkgs=`find . -maxdepth 1 -name "${package_name}.????" | wc -l`
